on: [push, pull_request]
name: test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.0-rc1]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: '!contains(${{ matrix.go-version }}, "beta") && !contains(${{ matrix.go-version }}, "rc")'
        go-version: ${{ matrix.go-version }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run esbuild
      run: bash -x ./scripts/setup-test-cra-app.sh
    - name: Test
      run: go test -race ./...
