on: [push, pull_request]
name: test

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run esbuild
      run: ./scripts/setup-test-cra-app.sh
    - name: Test
      run: go test -race ./...
